services:
  - type: web
    name: mart-az-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run render-build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - type: web
    name: mart-az-backend
    env: node
    buildCommand: >
      cd backend && 
      npm install && 
      npm run emergency:create-tables && 
      npm run render:migrate && 
      npm run render:db:setup
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: RUN_MIGRATIONS
        value: true
      - key: RUN_SEEDERS
        value: true
      # Database configuration with multiple naming conventions
      - key: DB_HOST
        value: dpg-cvi8s6pr0fns73c407tg-a
      - key: DATABASE_HOST
        value: dpg-cvi8s6pr0fns73c407tg-a
      - key: PGHOST
        value: dpg-cvi8s6pr0fns73c407tg-a
        
      - key: DB_PORT
        value: 5432
      - key: DATABASE_PORT
        value: 5432
      - key: PGPORT
        value: 5432
        
      - key: DB_NAME
        value: martaz_cxju
      - key: DATABASE_NAME
        value: martaz_cxju
      - key: PGDATABASE
        value: martaz_cxju
        
      - key: DB_USERNAME
        value: martaz
      - key: DB_USER
        value: martaz
      - key: PGUSER
        value: martaz
        
      - key: DB_PASSWORD
        value: 510O4GNI0s70CRxsgvr5Rpe2B1UCi2Q8
      - key: DATABASE_PASSWORD
        value: 510O4GNI0s70CRxsgvr5Rpe2B1UCi2Q8
      - key: PGPASSWORD
        value: 510O4GNI0s70CRxsgvr5Rpe2B1UCi2Q8
        
      - key: PGSSLMODE
        value: no-verify
      - key: JWT_SECRET
        value: mart-az-super-secret-key-for-production-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://mart-az-frontend.onrender.com
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://mart-az-frontend.onrender.com
      - key: LOG_LEVEL
        value: debug
      - key: FORCE_INIT
        value: true
    healthCheckPath: /api/health 
