services:
  - type: web
    name: mart-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://api.mart.az
  - type: web
    name: mart-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://user:password@db.mart.az:5432/mart
databases:
  - name: mart-database
    plan: free
   