services:
  - type: web
    name: mart
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://mart-backend-g0vt.onrender.com
  - type: web
    name: mart-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://mart_database_user:I4MQVDPXfyMgEi81KU32gqhWJ97jMxZe@dpg-d07ut19r0fns73a6ch4g-a.oregon-postgres.render.com/mart_database
databases:
  - name: mart-database
    plan: free
   